#!/bin/sh

if [ \$(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ \$(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi

BASEDIR=`dirname \$(\$pathCmd \$0)`

. \$BASEDIR/setEnv

exec \$APP_CMD $package$.Main "\$@"
